# Template file for passing OAuth authentication credentials and cookie to
# reddit-dl.
#
# Use the -x or --auth option to pass credentials file to reddit-dl:
#
# reddit-dl -x /path/to/auth/file ...
#
# Make sure you keep the file secured!

# ===========================================================================
# OAuth
# ===========================================================================
#
# OAuth credentials consist of a "client ID" and "secret". If provided, they
# will be used to request data from Reddit's API.
#
# Unfortunately, Reddit has effectively closed its API application to the
# general public. This means if you don't already have the relevant OAuth
# credentials, it is unlikely you will be able to obtain any.
#
# If you do possess valid credentials, you can provide them to reddit-dl. You
# would also need to provide the username and password of your Reddit account,
# which should be the same as the one used to apply for the credentials.

client.id =
client.secret =
username =
password =

# ===========================================================================
# Cookie
# ===========================================================================
#
# Providing a browser cookie associated with a logged-in account can help
# reddit-dl download Reddit-hosted videos at their highest quality. Without
# it, quality may be capped at 720p.
#
# The cookie can be found in the header of requests to reddit.com. You can use
# browser developer tools to find it.
#
# Note:
# - You should be signed in when obtaining the cookie.
# - You are recommended to use a dummy account, so your main account 
#   won't be affected if Reddit thinks you're a bot.
# - If you are downloading mature content, make sure you pass the
#   disclaimer in the browser first.
# - The cookie becomes invalid once you sign out in the browser.

cookie = 